name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    # Optional; to run only when a label is attached
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: Japanese
          # https://platform.openai.com/docs/models
          # MODEL: gpt-3.5-turbo
          MODEL: gpt-4
          PROMPT: 次のコード差分から①混乱や規則に従っていないコードがあるかどうか、②Rustのベストプラクティスに従うとどのようにコードを改善できるのか、③変数名や関数名で改善できる箇所があるのか、④不足しているテストケースやアサーションがないのか、⑤関数やクロージャーで独立化させるべき処理があるのか、を確認してそれぞれの観点に関する回答をそれぞれ出力してください
          top_p: 1
          temperature: 1
